apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiaccount
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apiRole
rules:
    - apiGroups: [""] 
      # "" indicates the core API group
      resources: ["deployments", "namespaces", "pods"]
      verbs: ["get", "list", "update", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apiaccountRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apiRole
subjects:
  - kind: ServiceAccount
    name: apiaccount